//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtoGenerator.Generator.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtoGenerator.Generator.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Test
        ///{
        ///    public sealed class SomethingBad 
        ///    {
        ///        public System.Int32 MyProperty { get; set; }
        ///        public System.Boolean OnlyMine { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SomethingBad {
            get {
                return ResourceManager.GetString("SomethingBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Test
        ///{
        ///    public sealed class SomethingBad1 
        ///    {
        ///        public System.Int32 MyProperty { get; set; }
        ///        public System.Boolean OnlyMine { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SomethingBad1 {
            get {
                return ResourceManager.GetString("SomethingBad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Test
        ///{
        ///    public sealed class SomethingWicked 
        ///    {
        ///        public System.Int32 FirstProperty { get; set; }
        ///        public System.Int64 SecondProperty { get; set; }
        ///        public System.Single ThirdProperty { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SomethingWicked {
            get {
                return ResourceManager.GetString("SomethingWicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Test
        ///{
        ///    public sealed class SomethingWicked1 
        ///    {
        ///        public System.Int64 SecondProperty { get; set; }
        ///        public System.Single ThirdProperty { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SomethingWicked1 {
            get {
                return ResourceManager.GetString("SomethingWicked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Test
        ///{
        ///    public sealed class SomethingWicked2 
        ///    {
        ///        public System.Int32 FirstProperty { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SomethingWicked2 {
            get {
                return ResourceManager.GetString("SomethingWicked2", resourceCulture);
            }
        }
    }
}
