//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonToDtoDeserializer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class GeneratorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneratorSettings defaultInstance = ((GeneratorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneratorSettings())));
        
        public static GeneratorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTO")]
        public string NamespaceName {
            get {
                return ((string)(this["NamespaceName"]));
            }
            set {
                this["NamespaceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaximumTaskNumber {
            get {
                return ((int)(this["MaximumTaskNumber"]));
            }
            set {
                this["MaximumTaskNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginsFolderName {
            get {
                return ((string)(this["PluginsFolderName"]));
            }
            set {
                this["PluginsFolderName"] = value;
            }
        }
    }
}
